# DO NOT EDIT THIS FILE!
#
# Python module server__POA generated by omniidl

import omniORB
omniORB.updateModule("server__POA")

# ** 1. Stub files contributing to this module
import Crawler_idl

# ** 2. Sub-modules

# ** 3. End
